version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "npm"
      - "type::chore"
    open-pull-requests-limit: 3
    assignees:
      - "asutermo"
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
      - "type::chore"
    assignees:
      - "asutermo"
    groups:
      github-actions:
        patterns:
          - "*"
